# -*- encoding: utf-8 -*-

=begin
#Crisphive Developer API

#Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "crisphive/version"

Gem::Specification.new do |s|
  s.name        = "crisphive"
  s.version     = Crisphive::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Crisphive"]
  s.email       = ["developer@crisphive.com"]
  s.homepage    = "https://docs.crisphive.com"
  s.summary     = "Official Ruby SDK for the Crisphive API"
  s.description = "Official Ruby SDK for the Crisphive API. Typed access to the public /v1 API - customers, bookings, catalog, team and fleet."
  s.license     = "MIT"
  s.required_ruby_version = ">= 2.7"
  s.metadata    = { "source_code_uri" => "https://github.com/crisphive/crisphive-ruby", "documentation_uri" => "https://docs.crisphive.com" }

  s.add_runtime_dependency 'faraday', '>= 1.0.1', '< 3.0'
  s.add_runtime_dependency 'faraday-multipart'
  s.add_runtime_dependency 'marcel'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.executables   = []
  s.require_paths = ["lib"]
end
