=begin
#CrispHive Developer API

#Public REST API for integrating CrispHive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

# Common files
require 'crisphive/api_client'
require 'crisphive/api_error'
require 'crisphive/version'
require 'crisphive/configuration'

# Models
require 'crisphive/models/create_customer200_response'
require 'crisphive/models/create_job_request200_response'
require 'crisphive/models/customer'
require 'crisphive/models/customer_address'
require 'crisphive/models/customer_address_request'
require 'crisphive/models/customer_contact'
require 'crisphive/models/customer_create_request'
require 'crisphive/models/customer_create_response'
require 'crisphive/models/customer_list'
require 'crisphive/models/customer_list_item'
require 'crisphive/models/customer_profile'
require 'crisphive/models/customer_spending'
require 'crisphive/models/customer_tier_progress'
require 'crisphive/models/customer_update_request'
require 'crisphive/models/date'
require 'crisphive/models/get_customer200_response'
require 'crisphive/models/get_job_request200_response'
require 'crisphive/models/get_job_request_timeline200_response'
require 'crisphive/models/get_job_type200_response'
require 'crisphive/models/get_service_area200_response'
require 'crisphive/models/get_technician200_response'
require 'crisphive/models/get_vehicle200_response'
require 'crisphive/models/job_date'
require 'crisphive/models/job_date_business_range'
require 'crisphive/models/job_date_period'
require 'crisphive/models/job_date_period_entry'
require 'crisphive/models/job_request'
require 'crisphive/models/job_request_action_audit_by'
require 'crisphive/models/job_request_action_audit_entry'
require 'crisphive/models/job_request_action_summary'
require 'crisphive/models/job_request_address_summary'
require 'crisphive/models/job_request_archive_summary'
require 'crisphive/models/job_request_arrival_window'
require 'crisphive/models/job_request_assigned_vehicle'
require 'crisphive/models/job_request_assignment_summary'
require 'crisphive/models/job_request_booking_windows'
require 'crisphive/models/job_request_business_time_range'
require 'crisphive/models/job_request_changes'
require 'crisphive/models/job_request_create_request'
require 'crisphive/models/job_request_create_response'
require 'crisphive/models/job_request_crew_member'
require 'crisphive/models/job_request_customer_summary'
require 'crisphive/models/job_request_day_windows'
require 'crisphive/models/job_request_job_date_business_range_request'
require 'crisphive/models/job_request_job_date_period_request'
require 'crisphive/models/job_request_job_date_request'
require 'crisphive/models/job_request_list'
require 'crisphive/models/job_request_period'
require 'crisphive/models/job_request_quote_summary'
require 'crisphive/models/job_request_rating_summary'
require 'crisphive/models/job_request_schedule'
require 'crisphive/models/job_request_session'
require 'crisphive/models/job_request_skill_summary'
require 'crisphive/models/job_request_status_summary'
require 'crisphive/models/job_request_technician_info'
require 'crisphive/models/job_request_timeline'
require 'crisphive/models/job_request_timeline_action'
require 'crisphive/models/job_request_timeline_event'
require 'crisphive/models/job_type'
require 'crisphive/models/list_customers200_response'
require 'crisphive/models/list_job_request_booking_windows200_response'
require 'crisphive/models/list_job_request_changes200_response'
require 'crisphive/models/list_job_requests200_response'
require 'crisphive/models/list_job_types200_response'
require 'crisphive/models/list_service_areas200_response'
require 'crisphive/models/list_skill_categories200_response'
require 'crisphive/models/list_skills200_response'
require 'crisphive/models/list_skills_by_category200_response'
require 'crisphive/models/list_technicians200_response'
require 'crisphive/models/list_vehicles200_response'
require 'crisphive/models/pagination'
require 'crisphive/models/response_envelope'
require 'crisphive/models/service_area'
require 'crisphive/models/service_area_list'
require 'crisphive/models/skill'
require 'crisphive/models/skill_by_category_list'
require 'crisphive/models/skill_category'
require 'crisphive/models/skill_category_list'
require 'crisphive/models/skill_list'
require 'crisphive/models/skill_summary'
require 'crisphive/models/technician'
require 'crisphive/models/technician_address'
require 'crisphive/models/technician_lead_ref'
require 'crisphive/models/technician_list'
require 'crisphive/models/technician_service_area_ref'
require 'crisphive/models/technician_status'
require 'crisphive/models/vehicle'
require 'crisphive/models/vehicle_list'
require 'crisphive/models/vehicle_owner'

# APIs
require 'crisphive/api/business_skill_api'
require 'crisphive/api/customer_api'
require 'crisphive/api/job_request_business_api'
require 'crisphive/api/job_types_api'
require 'crisphive/api/service_area_api'
require 'crisphive/api/technician_api'
require 'crisphive/api/vehicle_api'

module Crisphive
  class << self
    # Customize default settings for the SDK using block.
    #   Crisphive.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
