=begin
#Crisphive Developer API

#Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

require 'date'
require 'time'

module Crisphive
  class CustomerAddressRequest
    # City / locality. Max 100 chars.
    attr_accessor :city

    # Country (free-form or ISO code). Max 100 chars.
    attr_accessor :country

    # Human-readable single-line address; when set it wins over the discrete parts for display. Max 500 chars.
    attr_accessor :formatted

    # Geographic latitude in decimal degrees (-90..90). Omit if unknown.
    attr_accessor :latitude

    # Street address, line 1 (e.g. \"123 Main St\"). Max 255 chars.
    attr_accessor :line

    # Street address, line 2 (apartment, suite, unit). Max 255 chars.
    attr_accessor :line2

    # Geographic longitude in decimal degrees (-180..180). Omit if unknown.
    attr_accessor :longitude

    # Postal / ZIP code. Max 32 chars.
    attr_accessor :postal_code

    # State / province / region. Max 100 chars.
    attr_accessor :state

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'city' => :'city',
        :'country' => :'country',
        :'formatted' => :'formatted',
        :'latitude' => :'latitude',
        :'line' => :'line',
        :'line2' => :'line2',
        :'longitude' => :'longitude',
        :'postal_code' => :'postal_code',
        :'state' => :'state'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'city' => :'String',
        :'country' => :'String',
        :'formatted' => :'String',
        :'latitude' => :'Float',
        :'line' => :'String',
        :'line2' => :'String',
        :'longitude' => :'Float',
        :'postal_code' => :'String',
        :'state' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Crisphive::CustomerAddressRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Crisphive::CustomerAddressRequest`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'city')
        self.city = attributes[:'city']
      end

      if attributes.key?(:'country')
        self.country = attributes[:'country']
      end

      if attributes.key?(:'formatted')
        self.formatted = attributes[:'formatted']
      end

      if attributes.key?(:'latitude')
        self.latitude = attributes[:'latitude']
      end

      if attributes.key?(:'line')
        self.line = attributes[:'line']
      end

      if attributes.key?(:'line2')
        self.line2 = attributes[:'line2']
      end

      if attributes.key?(:'longitude')
        self.longitude = attributes[:'longitude']
      end

      if attributes.key?(:'postal_code')
        self.postal_code = attributes[:'postal_code']
      end

      if attributes.key?(:'state')
        self.state = attributes[:'state']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@city.nil? && @city.to_s.length > 100
        invalid_properties.push('invalid value for "city", the character length must be smaller than or equal to 100.')
      end

      if !@country.nil? && @country.to_s.length > 100
        invalid_properties.push('invalid value for "country", the character length must be smaller than or equal to 100.')
      end

      if !@formatted.nil? && @formatted.to_s.length > 500
        invalid_properties.push('invalid value for "formatted", the character length must be smaller than or equal to 500.')
      end

      if !@latitude.nil? && @latitude > 90
        invalid_properties.push('invalid value for "latitude", must be smaller than or equal to 90.')
      end

      if !@latitude.nil? && @latitude < -90
        invalid_properties.push('invalid value for "latitude", must be greater than or equal to -90.')
      end

      if !@line.nil? && @line.to_s.length > 255
        invalid_properties.push('invalid value for "line", the character length must be smaller than or equal to 255.')
      end

      if !@line2.nil? && @line2.to_s.length > 255
        invalid_properties.push('invalid value for "line2", the character length must be smaller than or equal to 255.')
      end

      if !@longitude.nil? && @longitude > 180
        invalid_properties.push('invalid value for "longitude", must be smaller than or equal to 180.')
      end

      if !@longitude.nil? && @longitude < -180
        invalid_properties.push('invalid value for "longitude", must be greater than or equal to -180.')
      end

      if !@postal_code.nil? && @postal_code.to_s.length > 32
        invalid_properties.push('invalid value for "postal_code", the character length must be smaller than or equal to 32.')
      end

      if !@state.nil? && @state.to_s.length > 100
        invalid_properties.push('invalid value for "state", the character length must be smaller than or equal to 100.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@city.nil? && @city.to_s.length > 100
      return false if !@country.nil? && @country.to_s.length > 100
      return false if !@formatted.nil? && @formatted.to_s.length > 500
      return false if !@latitude.nil? && @latitude > 90
      return false if !@latitude.nil? && @latitude < -90
      return false if !@line.nil? && @line.to_s.length > 255
      return false if !@line2.nil? && @line2.to_s.length > 255
      return false if !@longitude.nil? && @longitude > 180
      return false if !@longitude.nil? && @longitude < -180
      return false if !@postal_code.nil? && @postal_code.to_s.length > 32
      return false if !@state.nil? && @state.to_s.length > 100
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] city Value to be assigned
    def city=(city)
      if city.nil?
        fail ArgumentError, 'city cannot be nil'
      end

      if city.to_s.length > 100
        fail ArgumentError, 'invalid value for "city", the character length must be smaller than or equal to 100.'
      end

      @city = city
    end

    # Custom attribute writer method with validation
    # @param [Object] country Value to be assigned
    def country=(country)
      if country.nil?
        fail ArgumentError, 'country cannot be nil'
      end

      if country.to_s.length > 100
        fail ArgumentError, 'invalid value for "country", the character length must be smaller than or equal to 100.'
      end

      @country = country
    end

    # Custom attribute writer method with validation
    # @param [Object] formatted Value to be assigned
    def formatted=(formatted)
      if formatted.nil?
        fail ArgumentError, 'formatted cannot be nil'
      end

      if formatted.to_s.length > 500
        fail ArgumentError, 'invalid value for "formatted", the character length must be smaller than or equal to 500.'
      end

      @formatted = formatted
    end

    # Custom attribute writer method with validation
    # @param [Object] latitude Value to be assigned
    def latitude=(latitude)
      if latitude.nil?
        fail ArgumentError, 'latitude cannot be nil'
      end

      if latitude > 90
        fail ArgumentError, 'invalid value for "latitude", must be smaller than or equal to 90.'
      end

      if latitude < -90
        fail ArgumentError, 'invalid value for "latitude", must be greater than or equal to -90.'
      end

      @latitude = latitude
    end

    # Custom attribute writer method with validation
    # @param [Object] line Value to be assigned
    def line=(line)
      if line.nil?
        fail ArgumentError, 'line cannot be nil'
      end

      if line.to_s.length > 255
        fail ArgumentError, 'invalid value for "line", the character length must be smaller than or equal to 255.'
      end

      @line = line
    end

    # Custom attribute writer method with validation
    # @param [Object] line2 Value to be assigned
    def line2=(line2)
      if line2.nil?
        fail ArgumentError, 'line2 cannot be nil'
      end

      if line2.to_s.length > 255
        fail ArgumentError, 'invalid value for "line2", the character length must be smaller than or equal to 255.'
      end

      @line2 = line2
    end

    # Custom attribute writer method with validation
    # @param [Object] longitude Value to be assigned
    def longitude=(longitude)
      if longitude.nil?
        fail ArgumentError, 'longitude cannot be nil'
      end

      if longitude > 180
        fail ArgumentError, 'invalid value for "longitude", must be smaller than or equal to 180.'
      end

      if longitude < -180
        fail ArgumentError, 'invalid value for "longitude", must be greater than or equal to -180.'
      end

      @longitude = longitude
    end

    # Custom attribute writer method with validation
    # @param [Object] postal_code Value to be assigned
    def postal_code=(postal_code)
      if postal_code.nil?
        fail ArgumentError, 'postal_code cannot be nil'
      end

      if postal_code.to_s.length > 32
        fail ArgumentError, 'invalid value for "postal_code", the character length must be smaller than or equal to 32.'
      end

      @postal_code = postal_code
    end

    # Custom attribute writer method with validation
    # @param [Object] state Value to be assigned
    def state=(state)
      if state.nil?
        fail ArgumentError, 'state cannot be nil'
      end

      if state.to_s.length > 100
        fail ArgumentError, 'invalid value for "state", the character length must be smaller than or equal to 100.'
      end

      @state = state
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          city == o.city &&
          country == o.country &&
          formatted == o.formatted &&
          latitude == o.latitude &&
          line == o.line &&
          line2 == o.line2 &&
          longitude == o.longitude &&
          postal_code == o.postal_code &&
          state == o.state
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [city, country, formatted, latitude, line, line2, longitude, postal_code, state].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Crisphive.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
