=begin
#Crisphive Developer API

#Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

require 'date'
require 'time'

module Crisphive
  class JobRequestAbsenceResolvedJob
    # Commit only, when the placement came from unresolved[].alternatives[]: the accepted kind. Absent for a strict placement. EXTEND-ONLY.
    attr_accessor :alternative_kind

    # Commit only: the job's \"needs attention\" flag was cleared in the same write.
    attr_accessor :attention_cleared

    # Minutes the alternate already has booked that day (load).
    attr_accessor :booked_minutes

    # Commit only, with alternative_kind: what the business paid for this placement.
    attr_accessor :cost

    # Customer name on the job.
    attr_accessor :customer_name

    # Business-local calendar day the window starts on (YYYY-MM-DD) — group a multi-day range on it.
    attr_accessor :date

    attr_accessor :desired_skills

    # Alternate's driving distance to the site in km. ABSENT when the engine had no route (no start location, no job coordinates, routing failure) — hide the chip rather than rendering \"0 km\".
    attr_accessor :distance_km

    # Window end (UTC).
    attr_accessor :end_at

    # How many alternates could have taken this job.
    attr_accessor :feasible_count

    # UUID of the absent technician losing the job.
    attr_accessor :from_technician_id

    # UUID of the re-staffed job.
    attr_accessor :job_id

    # Desired skills the alternate holds / the job asks for.
    attr_accessor :matched_skills

    # Commit only: what the customer-notification routing will do for this job.
    attr_accessor :notification

    attr_accessor :original_end_at

    # Commit only, when window_preserved is false: the window the job LEFT (UTC).
    attr_accessor :original_start_at

    # Priority (p0..p3).
    attr_accessor :priority

    # Human-friendly short code.
    attr_accessor :short_code

    # Window start (UTC). For a strict or reassign_out_of_area placement it is byte-identical to the job's current window; for an accepted reschedule alternative (commit) it is the NEW window.
    attr_accessor :start_at

    # status_version: at preview the current value (echo it on commit); on the COMMIT response the post-commit value (+1).
    attr_accessor :status_version

    # Full name of the alternate. Omitted when unresolved.
    attr_accessor :to_name

    # UUID of the alternate receiving the job.
    attr_accessor :to_technician_id

    # Engine ranking score for this alternate on this job (0..1).
    attr_accessor :total_score

    # Alternate's one-way commute estimate in minutes (rounded up). Absent when unknown.
    attr_accessor :travel_minutes

    # True unless the coordinator accepted a reschedule alternative — then false, and original_start_at/original_end_at carry the window the job left.
    attr_accessor :window_preserved

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'alternative_kind' => :'alternative_kind',
        :'attention_cleared' => :'attention_cleared',
        :'booked_minutes' => :'booked_minutes',
        :'cost' => :'cost',
        :'customer_name' => :'customer_name',
        :'date' => :'date',
        :'desired_skills' => :'desired_skills',
        :'distance_km' => :'distance_km',
        :'end_at' => :'end_at',
        :'feasible_count' => :'feasible_count',
        :'from_technician_id' => :'from_technician_id',
        :'job_id' => :'job_id',
        :'matched_skills' => :'matched_skills',
        :'notification' => :'notification',
        :'original_end_at' => :'original_end_at',
        :'original_start_at' => :'original_start_at',
        :'priority' => :'priority',
        :'short_code' => :'short_code',
        :'start_at' => :'start_at',
        :'status_version' => :'status_version',
        :'to_name' => :'to_name',
        :'to_technician_id' => :'to_technician_id',
        :'total_score' => :'total_score',
        :'travel_minutes' => :'travel_minutes',
        :'window_preserved' => :'window_preserved'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'alternative_kind' => :'String',
        :'attention_cleared' => :'Boolean',
        :'booked_minutes' => :'Integer',
        :'cost' => :'JobRequestAbsenceAlternativeCost',
        :'customer_name' => :'String',
        :'date' => :'Date',
        :'desired_skills' => :'Integer',
        :'distance_km' => :'Float',
        :'end_at' => :'Time',
        :'feasible_count' => :'Integer',
        :'from_technician_id' => :'String',
        :'job_id' => :'String',
        :'matched_skills' => :'Integer',
        :'notification' => :'JobRequestAbsenceNotification',
        :'original_end_at' => :'Time',
        :'original_start_at' => :'Time',
        :'priority' => :'String',
        :'short_code' => :'String',
        :'start_at' => :'Time',
        :'status_version' => :'Integer',
        :'to_name' => :'String',
        :'to_technician_id' => :'String',
        :'total_score' => :'Float',
        :'travel_minutes' => :'Integer',
        :'window_preserved' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Crisphive::JobRequestAbsenceResolvedJob` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Crisphive::JobRequestAbsenceResolvedJob`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'alternative_kind')
        self.alternative_kind = attributes[:'alternative_kind']
      end

      if attributes.key?(:'attention_cleared')
        self.attention_cleared = attributes[:'attention_cleared']
      end

      if attributes.key?(:'booked_minutes')
        self.booked_minutes = attributes[:'booked_minutes']
      end

      if attributes.key?(:'cost')
        self.cost = attributes[:'cost']
      end

      if attributes.key?(:'customer_name')
        self.customer_name = attributes[:'customer_name']
      end

      if attributes.key?(:'date')
        self.date = attributes[:'date']
      end

      if attributes.key?(:'desired_skills')
        self.desired_skills = attributes[:'desired_skills']
      end

      if attributes.key?(:'distance_km')
        self.distance_km = attributes[:'distance_km']
      end

      if attributes.key?(:'end_at')
        self.end_at = attributes[:'end_at']
      end

      if attributes.key?(:'feasible_count')
        self.feasible_count = attributes[:'feasible_count']
      end

      if attributes.key?(:'from_technician_id')
        self.from_technician_id = attributes[:'from_technician_id']
      end

      if attributes.key?(:'job_id')
        self.job_id = attributes[:'job_id']
      end

      if attributes.key?(:'matched_skills')
        self.matched_skills = attributes[:'matched_skills']
      end

      if attributes.key?(:'notification')
        self.notification = attributes[:'notification']
      end

      if attributes.key?(:'original_end_at')
        self.original_end_at = attributes[:'original_end_at']
      end

      if attributes.key?(:'original_start_at')
        self.original_start_at = attributes[:'original_start_at']
      end

      if attributes.key?(:'priority')
        self.priority = attributes[:'priority']
      end

      if attributes.key?(:'short_code')
        self.short_code = attributes[:'short_code']
      end

      if attributes.key?(:'start_at')
        self.start_at = attributes[:'start_at']
      end

      if attributes.key?(:'status_version')
        self.status_version = attributes[:'status_version']
      end

      if attributes.key?(:'to_name')
        self.to_name = attributes[:'to_name']
      end

      if attributes.key?(:'to_technician_id')
        self.to_technician_id = attributes[:'to_technician_id']
      end

      if attributes.key?(:'total_score')
        self.total_score = attributes[:'total_score']
      end

      if attributes.key?(:'travel_minutes')
        self.travel_minutes = attributes[:'travel_minutes']
      end

      if attributes.key?(:'window_preserved')
        self.window_preserved = attributes[:'window_preserved']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      alternative_kind_validator = EnumAttributeValidator.new('String', ["reassign_out_of_area", "reschedule_same_day", "reschedule_later_day"])
      return false unless alternative_kind_validator.valid?(@alternative_kind)
      priority_validator = EnumAttributeValidator.new('String', ["p0", "p1", "p2", "p3"])
      return false unless priority_validator.valid?(@priority)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] alternative_kind Object to be assigned
    def alternative_kind=(alternative_kind)
      validator = EnumAttributeValidator.new('String', ["reassign_out_of_area", "reschedule_same_day", "reschedule_later_day"])
      unless validator.valid?(alternative_kind)
        fail ArgumentError, "invalid value for \"alternative_kind\", must be one of #{validator.allowable_values}."
      end
      @alternative_kind = alternative_kind
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] priority Object to be assigned
    def priority=(priority)
      validator = EnumAttributeValidator.new('String', ["p0", "p1", "p2", "p3"])
      unless validator.valid?(priority)
        fail ArgumentError, "invalid value for \"priority\", must be one of #{validator.allowable_values}."
      end
      @priority = priority
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          alternative_kind == o.alternative_kind &&
          attention_cleared == o.attention_cleared &&
          booked_minutes == o.booked_minutes &&
          cost == o.cost &&
          customer_name == o.customer_name &&
          date == o.date &&
          desired_skills == o.desired_skills &&
          distance_km == o.distance_km &&
          end_at == o.end_at &&
          feasible_count == o.feasible_count &&
          from_technician_id == o.from_technician_id &&
          job_id == o.job_id &&
          matched_skills == o.matched_skills &&
          notification == o.notification &&
          original_end_at == o.original_end_at &&
          original_start_at == o.original_start_at &&
          priority == o.priority &&
          short_code == o.short_code &&
          start_at == o.start_at &&
          status_version == o.status_version &&
          to_name == o.to_name &&
          to_technician_id == o.to_technician_id &&
          total_score == o.total_score &&
          travel_minutes == o.travel_minutes &&
          window_preserved == o.window_preserved
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [alternative_kind, attention_cleared, booked_minutes, cost, customer_name, date, desired_skills, distance_km, end_at, feasible_count, from_technician_id, job_id, matched_skills, notification, original_end_at, original_start_at, priority, short_code, start_at, status_version, to_name, to_technician_id, total_score, travel_minutes, window_preserved].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Crisphive.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
