=begin
#Crisphive Developer API

#Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

require 'date'
require 'time'

module Crisphive
  class JobRequestLeadCandidate
    # Minutes of job work already booked on this technician's schedule over the evaluated window (feeds the wrench-time score; lower = more open capacity).
    attr_accessor :booked_minutes

    # Per-slot ranked buddy pools that fit THIS lead (present only when include_buddies=true was requested).
    attr_accessor :buddies

    # Estimated one-way distance from the technician's start location to the job site, in km (routing-provider estimate, straight-line fallback). 0 when the job has no geocoded location.
    attr_accessor :distance_km

    # Technician's full display name.
    attr_accessor :full_name

    # How many of the job's desired skills this technician holds.
    attr_accessor :matched_skills

    # Per-day on-site session plan this technician would work for the job (ordered; one block for a single-day visit, several for multi-day).
    attr_accessor :sessions

    # UUID of the candidate technician.
    attr_accessor :technician_id

    # Overall ranking score (0-100): weighted blend of the distance, travel-time, wrench-time and skill sub-scores; candidates are listed best-first.
    attr_accessor :total_score

    # Estimated one-way travel time from the technician's start location to the job site, in minutes. 0 when the job has no geocoded location.
    attr_accessor :travel_minutes

    # Vehicles free for the job's window, ordered by this lead's preference (present only when include_vehicle=true was requested).
    attr_accessor :vehicles

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'booked_minutes' => :'booked_minutes',
        :'buddies' => :'buddies',
        :'distance_km' => :'distance_km',
        :'full_name' => :'full_name',
        :'matched_skills' => :'matched_skills',
        :'sessions' => :'sessions',
        :'technician_id' => :'technician_id',
        :'total_score' => :'total_score',
        :'travel_minutes' => :'travel_minutes',
        :'vehicles' => :'vehicles'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'booked_minutes' => :'Integer',
        :'buddies' => :'Array<JobRequestBuddySlotCandidates>',
        :'distance_km' => :'Float',
        :'full_name' => :'String',
        :'matched_skills' => :'Integer',
        :'sessions' => :'Array<JobRequestSession>',
        :'technician_id' => :'String',
        :'total_score' => :'Float',
        :'travel_minutes' => :'Float',
        :'vehicles' => :'Array<JobRequestAvailableVehicle>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Crisphive::JobRequestLeadCandidate` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Crisphive::JobRequestLeadCandidate`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'booked_minutes')
        self.booked_minutes = attributes[:'booked_minutes']
      end

      if attributes.key?(:'buddies')
        if (value = attributes[:'buddies']).is_a?(Array)
          self.buddies = value
        end
      end

      if attributes.key?(:'distance_km')
        self.distance_km = attributes[:'distance_km']
      end

      if attributes.key?(:'full_name')
        self.full_name = attributes[:'full_name']
      end

      if attributes.key?(:'matched_skills')
        self.matched_skills = attributes[:'matched_skills']
      end

      if attributes.key?(:'sessions')
        if (value = attributes[:'sessions']).is_a?(Array)
          self.sessions = value
        end
      end

      if attributes.key?(:'technician_id')
        self.technician_id = attributes[:'technician_id']
      end

      if attributes.key?(:'total_score')
        self.total_score = attributes[:'total_score']
      end

      if attributes.key?(:'travel_minutes')
        self.travel_minutes = attributes[:'travel_minutes']
      end

      if attributes.key?(:'vehicles')
        if (value = attributes[:'vehicles']).is_a?(Array)
          self.vehicles = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          booked_minutes == o.booked_minutes &&
          buddies == o.buddies &&
          distance_km == o.distance_km &&
          full_name == o.full_name &&
          matched_skills == o.matched_skills &&
          sessions == o.sessions &&
          technician_id == o.technician_id &&
          total_score == o.total_score &&
          travel_minutes == o.travel_minutes &&
          vehicles == o.vehicles
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [booked_minutes, buddies, distance_km, full_name, matched_skills, sessions, technician_id, total_score, travel_minutes, vehicles].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Crisphive.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
