=begin
#Crisphive Developer API

#Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

require 'date'
require 'time'

module Crisphive
  class Technician
    # Technician's start-location postal address.
    attr_accessor :address

    # Smart-assignment tier, or null if unset.
    attr_accessor :assignment_tier

    # UUIDs of this technician's buddies (the techs they prefer to work alongside).
    attr_accessor :buddy_ids

    # UUID of the permission group (role) this technician is assigned to.
    attr_accessor :business_group_id

    # UUID of the business this technician belongs to.
    attr_accessor :business_id

    # When the technician record was created (RFC3339).
    attr_accessor :created_at

    # Set (RFC3339) only when the technician has been soft-removed; omitted otherwise.
    attr_accessor :deleted_at

    # Email address; null if not set.
    attr_accessor :email

    # Technician's full name.
    attr_accessor :full_name

    # Technician membership UUID — the stable identifier used in every technician endpoint.
    attr_accessor :id

    # Free-form job title (e.g. \"Senior HVAC Technician\"). Empty if unset.
    attr_accessor :job_title

    # Date the technician joined (YYYY-MM-DD); null if unset.
    attr_accessor :join_date

    # When the technician last logged in (RFC3339); null if never.
    attr_accessor :last_login_at

    # Leads this technician is a buddy of (id + name).
    attr_accessor :leads

    # Phone number in the form it was supplied; null if not set.
    attr_accessor :phone

    # Resolved role/group name (e.g. \"Technician\", \"Owner\").
    attr_accessor :role

    # Service areas this technician is assigned to (id + name).
    attr_accessor :service_areas

    # Start-location latitude in decimal degrees; null if no coordinates are saved.
    attr_accessor :start_location_lat

    # Start-location longitude in decimal degrees; null if no coordinates are saved.
    attr_accessor :start_location_long

    # Where the technician's day starts: \"home\" (their address) or \"office\" (the business address). Null if unset.
    attr_accessor :start_location_type

    # Membership lifecycle status.
    attr_accessor :status

    # When the technician record was last modified (RFC3339).
    attr_accessor :updated_at

    # UUID of the underlying user account.
    attr_accessor :user_id

    # UUIDs of the vehicles this technician uses.
    attr_accessor :vehicle_ids

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'address' => :'address',
        :'assignment_tier' => :'assignment_tier',
        :'buddy_ids' => :'buddy_ids',
        :'business_group_id' => :'business_group_id',
        :'business_id' => :'business_id',
        :'created_at' => :'created_at',
        :'deleted_at' => :'deleted_at',
        :'email' => :'email',
        :'full_name' => :'full_name',
        :'id' => :'id',
        :'job_title' => :'job_title',
        :'join_date' => :'join_date',
        :'last_login_at' => :'last_login_at',
        :'leads' => :'leads',
        :'phone' => :'phone',
        :'role' => :'role',
        :'service_areas' => :'service_areas',
        :'start_location_lat' => :'start_location_lat',
        :'start_location_long' => :'start_location_long',
        :'start_location_type' => :'start_location_type',
        :'status' => :'status',
        :'updated_at' => :'updated_at',
        :'user_id' => :'user_id',
        :'vehicle_ids' => :'vehicle_ids'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'address' => :'TechnicianAddress',
        :'assignment_tier' => :'String',
        :'buddy_ids' => :'Array<String>',
        :'business_group_id' => :'String',
        :'business_id' => :'String',
        :'created_at' => :'Time',
        :'deleted_at' => :'Time',
        :'email' => :'String',
        :'full_name' => :'String',
        :'id' => :'String',
        :'job_title' => :'String',
        :'join_date' => :'Date',
        :'last_login_at' => :'Time',
        :'leads' => :'Array<TechnicianLeadRef>',
        :'phone' => :'String',
        :'role' => :'String',
        :'service_areas' => :'Array<TechnicianServiceAreaRef>',
        :'start_location_lat' => :'Float',
        :'start_location_long' => :'Float',
        :'start_location_type' => :'String',
        :'status' => :'TechnicianStatus',
        :'updated_at' => :'Time',
        :'user_id' => :'String',
        :'vehicle_ids' => :'Array<String>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Crisphive::Technician` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Crisphive::Technician`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'address')
        self.address = attributes[:'address']
      end

      if attributes.key?(:'assignment_tier')
        self.assignment_tier = attributes[:'assignment_tier']
      end

      if attributes.key?(:'buddy_ids')
        if (value = attributes[:'buddy_ids']).is_a?(Array)
          self.buddy_ids = value
        end
      end

      if attributes.key?(:'business_group_id')
        self.business_group_id = attributes[:'business_group_id']
      end

      if attributes.key?(:'business_id')
        self.business_id = attributes[:'business_id']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'deleted_at')
        self.deleted_at = attributes[:'deleted_at']
      end

      if attributes.key?(:'email')
        self.email = attributes[:'email']
      end

      if attributes.key?(:'full_name')
        self.full_name = attributes[:'full_name']
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'job_title')
        self.job_title = attributes[:'job_title']
      end

      if attributes.key?(:'join_date')
        self.join_date = attributes[:'join_date']
      end

      if attributes.key?(:'last_login_at')
        self.last_login_at = attributes[:'last_login_at']
      end

      if attributes.key?(:'leads')
        if (value = attributes[:'leads']).is_a?(Array)
          self.leads = value
        end
      end

      if attributes.key?(:'phone')
        self.phone = attributes[:'phone']
      end

      if attributes.key?(:'role')
        self.role = attributes[:'role']
      end

      if attributes.key?(:'service_areas')
        if (value = attributes[:'service_areas']).is_a?(Array)
          self.service_areas = value
        end
      end

      if attributes.key?(:'start_location_lat')
        self.start_location_lat = attributes[:'start_location_lat']
      end

      if attributes.key?(:'start_location_long')
        self.start_location_long = attributes[:'start_location_long']
      end

      if attributes.key?(:'start_location_type')
        self.start_location_type = attributes[:'start_location_type']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      end

      if attributes.key?(:'user_id')
        self.user_id = attributes[:'user_id']
      end

      if attributes.key?(:'vehicle_ids')
        if (value = attributes[:'vehicle_ids']).is_a?(Array)
          self.vehicle_ids = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      assignment_tier_validator = EnumAttributeValidator.new('String', ["lead", "buddy", "float"])
      return false unless assignment_tier_validator.valid?(@assignment_tier)
      start_location_type_validator = EnumAttributeValidator.new('String', ["home", "office"])
      return false unless start_location_type_validator.valid?(@start_location_type)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] assignment_tier Object to be assigned
    def assignment_tier=(assignment_tier)
      validator = EnumAttributeValidator.new('String', ["lead", "buddy", "float"])
      unless validator.valid?(assignment_tier)
        fail ArgumentError, "invalid value for \"assignment_tier\", must be one of #{validator.allowable_values}."
      end
      @assignment_tier = assignment_tier
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] start_location_type Object to be assigned
    def start_location_type=(start_location_type)
      validator = EnumAttributeValidator.new('String', ["home", "office"])
      unless validator.valid?(start_location_type)
        fail ArgumentError, "invalid value for \"start_location_type\", must be one of #{validator.allowable_values}."
      end
      @start_location_type = start_location_type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          address == o.address &&
          assignment_tier == o.assignment_tier &&
          buddy_ids == o.buddy_ids &&
          business_group_id == o.business_group_id &&
          business_id == o.business_id &&
          created_at == o.created_at &&
          deleted_at == o.deleted_at &&
          email == o.email &&
          full_name == o.full_name &&
          id == o.id &&
          job_title == o.job_title &&
          join_date == o.join_date &&
          last_login_at == o.last_login_at &&
          leads == o.leads &&
          phone == o.phone &&
          role == o.role &&
          service_areas == o.service_areas &&
          start_location_lat == o.start_location_lat &&
          start_location_long == o.start_location_long &&
          start_location_type == o.start_location_type &&
          status == o.status &&
          updated_at == o.updated_at &&
          user_id == o.user_id &&
          vehicle_ids == o.vehicle_ids
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [address, assignment_tier, buddy_ids, business_group_id, business_id, created_at, deleted_at, email, full_name, id, job_title, join_date, last_login_at, leads, phone, role, service_areas, start_location_lat, start_location_long, start_location_type, status, updated_at, user_id, vehicle_ids].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Crisphive.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
