=begin
#Crisphive Developer API

#Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

require 'date'
require 'time'

module Crisphive
  class Vehicle
    # Manufacturer / make (e.g. \"Ford\"). Empty if not set.
    attr_accessor :brand

    # UUID of the business that owns this vehicle.
    attr_accessor :business_id

    # When the vehicle record was created (RFC3339).
    attr_accessor :created_at

    # Current odometer reading; null if not tracked.
    attr_accessor :current_mileage

    # Set (RFC3339) only when the record has been soft-deleted; omitted otherwise.
    attr_accessor :deleted_at

    # Vehicle UUID — the stable identifier used in every vehicle endpoint.
    attr_accessor :id

    # Model name (e.g. \"Transit\"). Empty if not set.
    attr_accessor :model

    # Vehicle display name.
    attr_accessor :name

    # Live operational state derived from the vehicle's jobs: on_job = a job's scheduled window contains now (the vehicle is out working); assigned = attached to an upcoming/open job that is not in progress; other values mirror status.
    attr_accessor :operational_status

    # The technician who currently owns (claimed) this vehicle; null if unowned.
    attr_accessor :owner

    # License plate number. Empty if not set.
    attr_accessor :plate_number

    # Stored status. on_job here means \"attached to an open job\" (set at assignment, cleared at complete/archive/unassign) — see operational_status for the live state.
    attr_accessor :status

    # UUIDs of technicians who use this vehicle (derived from each technician's vehicle list). Empty array if none.
    attr_accessor :technician_ids

    # When the vehicle record was last modified (RFC3339).
    attr_accessor :updated_at

    # Percentage of capacity the vehicle is utilized (0–100).
    attr_accessor :utilization_percent

    # Vehicle category.
    attr_accessor :vehicle_type

    # Model year. Zero if not set.
    attr_accessor :year

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'brand' => :'brand',
        :'business_id' => :'business_id',
        :'created_at' => :'created_at',
        :'current_mileage' => :'current_mileage',
        :'deleted_at' => :'deleted_at',
        :'id' => :'id',
        :'model' => :'model',
        :'name' => :'name',
        :'operational_status' => :'operational_status',
        :'owner' => :'owner',
        :'plate_number' => :'plate_number',
        :'status' => :'status',
        :'technician_ids' => :'technician_ids',
        :'updated_at' => :'updated_at',
        :'utilization_percent' => :'utilization_percent',
        :'vehicle_type' => :'vehicle_type',
        :'year' => :'year'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'brand' => :'String',
        :'business_id' => :'String',
        :'created_at' => :'Time',
        :'current_mileage' => :'Integer',
        :'deleted_at' => :'Time',
        :'id' => :'String',
        :'model' => :'String',
        :'name' => :'String',
        :'operational_status' => :'String',
        :'owner' => :'VehicleOwner',
        :'plate_number' => :'String',
        :'status' => :'String',
        :'technician_ids' => :'Array<String>',
        :'updated_at' => :'Time',
        :'utilization_percent' => :'Integer',
        :'vehicle_type' => :'String',
        :'year' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Crisphive::Vehicle` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Crisphive::Vehicle`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'brand')
        self.brand = attributes[:'brand']
      end

      if attributes.key?(:'business_id')
        self.business_id = attributes[:'business_id']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'current_mileage')
        self.current_mileage = attributes[:'current_mileage']
      end

      if attributes.key?(:'deleted_at')
        self.deleted_at = attributes[:'deleted_at']
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'model')
        self.model = attributes[:'model']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'operational_status')
        self.operational_status = attributes[:'operational_status']
      end

      if attributes.key?(:'owner')
        self.owner = attributes[:'owner']
      end

      if attributes.key?(:'plate_number')
        self.plate_number = attributes[:'plate_number']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'technician_ids')
        if (value = attributes[:'technician_ids']).is_a?(Array)
          self.technician_ids = value
        end
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      end

      if attributes.key?(:'utilization_percent')
        self.utilization_percent = attributes[:'utilization_percent']
      end

      if attributes.key?(:'vehicle_type')
        self.vehicle_type = attributes[:'vehicle_type']
      end

      if attributes.key?(:'year')
        self.year = attributes[:'year']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      operational_status_validator = EnumAttributeValidator.new('String', ["inactive", "idle", "assigned", "on_job", "maintenance"])
      return false unless operational_status_validator.valid?(@operational_status)
      status_validator = EnumAttributeValidator.new('String', ["inactive", "idle", "on_job", "maintenance"])
      return false unless status_validator.valid?(@status)
      vehicle_type_validator = EnumAttributeValidator.new('String', ["van", "truck", "car"])
      return false unless vehicle_type_validator.valid?(@vehicle_type)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] operational_status Object to be assigned
    def operational_status=(operational_status)
      validator = EnumAttributeValidator.new('String', ["inactive", "idle", "assigned", "on_job", "maintenance"])
      unless validator.valid?(operational_status)
        fail ArgumentError, "invalid value for \"operational_status\", must be one of #{validator.allowable_values}."
      end
      @operational_status = operational_status
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["inactive", "idle", "on_job", "maintenance"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] vehicle_type Object to be assigned
    def vehicle_type=(vehicle_type)
      validator = EnumAttributeValidator.new('String', ["van", "truck", "car"])
      unless validator.valid?(vehicle_type)
        fail ArgumentError, "invalid value for \"vehicle_type\", must be one of #{validator.allowable_values}."
      end
      @vehicle_type = vehicle_type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          brand == o.brand &&
          business_id == o.business_id &&
          created_at == o.created_at &&
          current_mileage == o.current_mileage &&
          deleted_at == o.deleted_at &&
          id == o.id &&
          model == o.model &&
          name == o.name &&
          operational_status == o.operational_status &&
          owner == o.owner &&
          plate_number == o.plate_number &&
          status == o.status &&
          technician_ids == o.technician_ids &&
          updated_at == o.updated_at &&
          utilization_percent == o.utilization_percent &&
          vehicle_type == o.vehicle_type &&
          year == o.year
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [brand, business_id, created_at, current_mileage, deleted_at, id, model, name, operational_status, owner, plate_number, status, technician_ids, updated_at, utilization_percent, vehicle_type, year].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Crisphive.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
